parameters: {}
environment: {}
packages:
    - name: sample
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: hello
          binary: false
          main: ""
          runtime: python:default
          web: true
          webSecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {
            memory: 512,
            timeout: 2000
          }
    - name: okx
      shared: false
      environment: { }
      parameters: { }
      annotations: { }
      functions:
        - name: trading_account_balance
          binary: false
          main: ""
          runtime: python:default
          web: true
          webSecure: false
          parameters: { }
          environment: { }
          annotations: { }
          limits: {
            memory: 512,
            timeout: 2000
          }
        - name: trading_account_positions
          binary: false
          main: ""
          runtime: python:default
          web: true
          webSecure: false
          parameters: { }
          environment: { }
          annotations: { }
          limits: {
            memory: 512,
            timeout: 2000
          }
        - name: trading_account_bills_archive
          binary: false
          main: ""
          runtime: python:default
          web: true
          webSecure: false
          parameters: { }
          environment: { }
          annotations: { }
          limits: {
            memory: 512,
            timeout: 2000
          }
        - name: funding_account_currencies
          binary: false
          main: ""
          runtime: python:default
          web: true
          webSecure: false
          parameters: { }
          environment: { }
          annotations: { }
          limits: {
            memory: 512,
            timeout: 2000
          }
        - name: funding_account_balances
          binary: false
          main: ""
          runtime: python:default
          web: true
          webSecure: false
          parameters: { }
          environment: { }
          annotations: { }
          limits: {
            memory: 512,
            timeout: 2000
          }
        - name: funding_account_non_tradable_assets
          binary: false
          main: ""
          runtime: python:default
          web: true
          webSecure: false
          parameters: { }
          environment: { }
          annotations: { }
          limits: {
            memory: 512,
            timeout: 2000
          }
        - name: funding_account_asset_valuation
          binary: false
          main: ""
          runtime: python:default
          web: true
          webSecure: false
          parameters: { }
          environment: { }
          annotations: { }
          limits: {
            memory: 512,
            timeout: 2000
          }
        - name: trading_data_support_coin
          binary: false
          main: ""
          runtime: python:default
          web: true
          webSecure: false
          parameters: { }
          environment: { }
          annotations: { }
          limits: {
            memory: 512,
            timeout: 2000
          }