parameters: {}
environment: {}
packages:
    - name: sample
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: hello
          binary: false
          main: ""
          runtime: python:3.9
          web: true
          parameters: {}
          environment: {}
          annotations: {}
          limits: {
            memory: 512,
            timeout: 2000
          }
    - name: okx
      shared: false
      environment: { }
      parameters: { }
      annotations: { }
      functions:
        - name: account_balance
          binary: false
          main: ""
          runtime: python:3.9
          web: true
          parameters: { }
          environment: { }
          annotations: { }
          limits: {
            memory: 512,
            timeout: 2000
          }